version: '3'

volumes:
  elasticsearch:
    driver: local  

networks:
  backend:
    driver: bridge

services:
  web:
    container_name: elastic-web
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./project:/var/www/app
      - ./docker/web/site.conf:/etc/nginx/conf.d/site.conf
    networks:
      - backend

  app:
    container_name: elastic-app
    user: ${USER_UID}:${USER_GID}
    build: docker/app/.
    volumes:
      - ./project:/var/www/app
    networks:
      - backend

  elasticsearch:
    container_name: elastic
    image: 'elasticsearch:7.13.4'
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch:/usr/share/elasticsearch/data'
    networks:
      - backend
  
  kibana:
    container_name: elastic-kibana
    image: 'kibana:7.13.4'
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    ports:
      - '5601:5601'
    networks:
      - backend
    depends_on:
      - elasticsearch